# Generated by Django 5.0.7 on 2024-10-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tigressapp", "0003_remove_products_img_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="../static/imguploads/"
            ),
        ),
    ]
