# Generated by Django 5.0.7 on 2024-10-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tigressapp", "0005_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
