# Generated by Django 5.0.7 on 2024-10-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tigressapp", "0006_alter_products_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Dishe",
        ),
        migrations.DeleteModel(
            name="Dish",
        ),
    ]
