# Generated by Django 5.0.7 on 2024-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tigressapp", "0007_rename_products_dishe_delete_dish"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=255)),
                ("content", models.TextField()),
                ("last_edited", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Terms of Service", max_length=255)),
                ("content", models.TextField()),
                ("last_edited", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="dishe",
            name="allergens",
            field=models.CharField(default="No allergens", max_length=255),
        ),
    ]
